version: "3"

services:

  provider-a:
    build:
      context: provider-a
      dockerfile: Dockerfile
    command: make start
    restart: unless-stopped
    container_name: provider-a
    ports:
      - "9001:8000"
    env_file:
      - .env

  provider-b:
    build:
      context: provider-b
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: provider-b
    command: make start
    ports:
      - "9002:8000"
    env_file:
      - .env

  airflow_db:
    image: postgres:14.1-alpine
    container_name: airflow_db
    restart: unless-stopped
    ports:
      - '5577:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}

  airflow:
    build:
      context: airflow
      dockerfile: Dockerfile
    restart: unless-stopped
    command: make start
    container_name: airflow
    ports:
      - "9000:8000"
    depends_on:
      - provider-a
      - provider-b
      - airflow_db

    env_file:
      - .env
