version: "3"

services:
  provider-a:
    build:
      context: .
      dockerfile: provider-a/Dockerfile
    restart: unless-stopped
    container_name: provider_a
    ports:
      - "9001:9001"
#    env_file:
#      - provider-a/.env

  provider-b:
    build:
      context: .
      dockerfile: provider-b/Dockerfile
    restart: unless-stopped
    container_name: provider_b
    ports:
      - "9002:9002"
#    env_file:
#      - provider-b/.env

  airflow_db:
    image: postgres:14.1-alpine
    container_name: airflow_db
    restart: unless-stopped
    ports:
      - '5577:5432' # TODO pass port
    environment: # TODO pass secrets safely
      - POSTGRES_USER=airflow_db
      - POSTGRES_PASSWORD=airflow_db
      - POSTGRES_DB=airflow_db
      - POSTGRES_HOST=localhost

  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5677:5672'
      # HTTP management UI
      - '15677:15672'

  redis:
    image: redis:6.2.6-alpine
    hostname: localhost
    container_name: redis
    ports:
      - '6377:6379'

  airflow:
    build:
      context: .
      dockerfile: airflow/Dockerfile
#    restart: unless-stopped
    container_name: airflow
    ports:
      - "9000:9000"
#    env_file:
#      - airflow/.env
    depends_on:
      - provider-a
      - provider-b
      - airflow_db
      - rabbitmq
      - redis
