version: "3"

services:

  provider-a:
    build:
      context: .
      dockerfile: provider-a/Dockerfile
    command: make start
    restart: unless-stopped
    container_name: provider_a
    ports:
      - "9001:8000"
    env_file:
      - provider-a/.env

  provider-b:
    build:
      context: .
      dockerfile: provider-b/Dockerfile
    command: make start
    restart: unless-stopped
    container_name: provider_b
    ports:
      - "9002:8000"
    env_file:
      - provider-b/.env

  airflow_db:
    image: postgres:14.1-alpine
    container_name: airflow_db
    restart: unless-stopped
    ports:
      - '5577:5432' # TODO pass port
    environment: # TODO pass secrets safely
      - POSTGRES_USER=airflow_db
      - POSTGRES_PASSWORD=airflow_db
      - POSTGRES_DB=airflow_db
      - POSTGRES_HOST=localhost

#  airflow:
#    build:
#      context: .
#      dockerfile: airflow/Dockerfile
#    command: make start
#    restart: unless-stopped
#    container_name: airflow
#    ports:
#      - "9000:8000"
#    env_file:
#      - airflow/.env
#    depends_on:
#      - provider-a
#      - provider-b
#      - airflow_db
