"""currency

Revision ID: 921c6be662f3
Revises: c617776c54f1
Create Date: 2023-03-01 00:37:47.682952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column, Integer, String, Boolean, update, text, delete, bindparam, select
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.engine import Inspector


# revision identifiers, used by Alembic.
revision = '921c6be662f3'
down_revision = 'c617776c54f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('uix_rate_currency_id', 'rate', type_='unique')
    op.add_column('rate', sa.Column('currency', sa.String(length=3), nullable=False))
    op.create_unique_constraint('uix_rate_currency', 'rate', ['currency'])
    op.drop_constraint('rate_currency_id_fkey', 'rate', type_='foreignkey')
    op.drop_column('rate', 'currency_id')
    op.drop_table('currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='currency_pkey'),
    sa.UniqueConstraint('code', name='uix_currency_code')
    )

    op.add_column('rate', sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('rate_currency_id_fkey', 'rate', 'currency', ['currency_id'], ['id'])
    op.drop_constraint('uix_rate_currency', 'rate', type_='unique')
    op.create_unique_constraint('uix_rate_currency_id', 'rate', ['currency_id'])
    op.drop_column('rate', 'currency')
    # ### end Alembic commands ###
