"""rate

Revision ID: c617776c54f1
Revises: 7058801e0fe0
Create Date: 2023-02-28 23:59:13.195709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column, Integer, String, Boolean, update, text, delete, bindparam, select
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.engine import Inspector


# revision identifiers, used by Alembic.
revision = 'c617776c54f1'
down_revision = '7058801e0fe0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_rate_currency_id_date', 'rate', type_='unique')
    op.create_unique_constraint('uix_rate_currency_id', 'rate', ['currency_id'])
    op.drop_column('rate', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint('uix_rate_currency_id', 'rate', type_='unique')
    op.create_unique_constraint('uix_rate_currency_id_date', 'rate', ['currency_id', 'date'])
    # ### end Alembic commands ###
