"""rate

Revision ID: 47eda912d49f
Revises: 20a03a9a35c3
Create Date: 2023-02-26 19:14:32.326553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column, Integer, String, Boolean, update, text, delete, bindparam, select
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.engine import Inspector


# revision identifiers, used by Alembic.
revision = '47eda912d49f'
down_revision = '20a03a9a35c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('quant', sa.DECIMAL(), nullable=False),
    sa.Column('quant_kzt', sa.DECIMAL(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], name='rate_currency_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate')
    op.drop_table('currency')
    # ### end Alembic commands ###
